@host=http://localhost:3000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikpvbm8iLCJpYXQiOjE2NTM5MjUyNjQsImV4cCI6MTY1MzkzMjQ2NH0.8iQ_qrZmaSxZvxulWfGqp5Ql5ZdVqfK8uMv0yUBRylM

###

POST {{host}}/login
Content-Type: application/x-www-form-urlencoded

username=Jono

###

GET {{host}}/todos

###

POST {{host}}/todos
Content-Type: application/x-www-form-urlencoded
access_token: {{token}}

todoName=Belajar Mata-mata